/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\public\models\boats0.1.gltf 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { Character } from "./Character";

export function Boats(props) {
	const { nodes, materials } = useGLTF("./models/boats0.2.gltf");
	return (
		<group {...props} dispose={null}>
			<group position={[9.104, 0, -0.164]}>
				<mesh
					geometry={nodes.Sphere002.geometry}
					material={materials["Master Pallet"]}
				/>
				<mesh
					geometry={nodes.Sphere002_1.geometry}
					material={materials.House_Mat}
				/>
			</group>

			{/* submarine */}
			<mesh
				geometry={nodes.Subrine.geometry}
				material={materials["Master Pallet"]}
				position={[-2.152, 0, -1.458]}
				rotation={[Math.PI, 0, Math.PI]}
			>
				<Character
					position={[0, 0.5, 0]}
					rotation={[0, Math.PI, 0]}
					visible={false}
				/>
			</mesh>

			<mesh
				geometry={nodes.Plane.geometry}
				material={materials["Master Pallet"]}
				position={[2.021, 0.004, -3.161]}
			>
				<Character
					position={[0, 0.5, 2.5]}
					rotation={[0, 0, 0]}
					visible={false}
				/>
			</mesh>
			<mesh
				geometry={nodes.Plane001.geometry}
				material={materials["Master Pallet"]}
				position={[5.8, 0.004, -3.161]}
			/>
		</group>
	);
}

useGLTF.preload("./models/boats0.2.gltf");
