/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\public\models\Character.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Character(props) {
  const { nodes, materials } = useGLTF('./models/Character.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sphere007.geometry} material={materials.SkinMat} />
      <mesh geometry={nodes.Sphere007_1.geometry} material={materials.GlassMat} />
    </group>
  )
}

useGLTF.preload('./models/Character.gltf')
