/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\public\models\Islands.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Islands(props) {
  const { nodes, materials } = useGLTF('./public/models/Islands.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Circle002.geometry} material={materials['Master Pallet']} position={[-33.775, 16.476, 4.767]} />
      <mesh geometry={nodes.Circle003.geometry} material={materials['Master Pallet']} position={[-33.775, 22.191, 4.767]} />
      <mesh geometry={nodes.Project_IsLand.geometry} material={materials['Master Pallet']} />
      <mesh geometry={nodes.Project_Building.geometry} material={materials['Master Pallet']} />
      <mesh geometry={nodes.Retopo_Text002.geometry} material={materials['TEXT.001']} rotation={[2.487, 0, Math.PI]} />
      <mesh geometry={nodes.Project_IsLand001.geometry} material={materials['Master Pallet']} position={[-34.97, -0.073, 5.42]} />
      <mesh geometry={nodes.Retopo_Text001.geometry} material={materials['TEXT.001']} rotation={[0, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.Cube.geometry} material={materials['Master Pallet']} position={[-8.826, -0.124, -32.605]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials['Master Pallet']} position={[15.186, 0.301, -19.835]} rotation={[0, 0, -0.151]} />
      <mesh geometry={nodes.Cube002.geometry} material={materials['Master Pallet']} position={[7.973, 2.338, -19.773]} rotation={[0, 0, -0.151]} />
      <mesh geometry={nodes.Cube003.geometry} material={materials['Master Pallet']} position={[15.323, -0.748, -23.455]} />
      <mesh geometry={nodes.Cube005.geometry} material={materials['Master Pallet']} position={[5.676, 3.051, -18.196]} />
      <mesh geometry={nodes.Project_Building001.geometry} material={materials['Master Pallet']} position={[-9.692, 1.139, -24.732]} />
      <mesh geometry={nodes.Retopo_Text003.geometry} material={materials['TEXT.001']} position={[-9.841, 10.217, -26.914]} rotation={[2.497, 0, Math.PI]} />
      <mesh geometry={nodes.Retopo_Text004.geometry} material={materials['TEXT.001']} position={[-5.626, 6.758, -24.732]} rotation={[Math.PI / 2, 0.926, -Math.PI / 2]} />
      <mesh geometry={nodes.Water_Plane.geometry} material={materials['Master Pallet']} position={[0,-0.5,0]}/>
    </group>
  )
}

useGLTF.preload('./public/models/Islands.gltf')
