/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\public\models\projectIsland.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function ProjectIsland(props) {
  const { nodes, materials } = useGLTF('./models/projectIsland.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Project_IsLand.geometry} material={materials['Master Pallet']} position={[0, -0.003, 0]} />
      <mesh geometry={nodes.Project_Building.geometry} material={materials['Master Pallet']} position={[-0.191, 0.169, -0.009]} />
      <mesh geometry={nodes.Retopo_Text002.geometry} material={materials['TEXT.001']} position={[-0.19, 0.518, -0.084]} rotation={[2.487, 0, Math.PI]} />
    </group>
  )
}

useGLTF.preload('./models/projectIsland.gltf')
