/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\public\models\train.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Train(props) {
  const { nodes, materials } = useGLTF('./models/train.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.train_cabinet.geometry} material={materials['Master Pallet']} position={[0, -0.5, 0]} scale={0.05} rotation={[0, -Math.PI/2, -Math.PI/2]}/>
      <mesh geometry={nodes.Train_Engine.geometry} material={materials['Master Pallet']} position={[0, 0, 0]} scale={0.1} rotation={[0, -Math.PI/2, -Math.PI/2]}/>
    </group>
  )
}

useGLTF.preload('./models/train.gltf')
