/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\public\models\train.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/train.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.train_cabinet.geometry} material={materials['Master Pallet']} position={[18.263, 0.23, 0]} />
      <mesh geometry={nodes.Train_Engine.geometry} material={materials['Master Pallet']} position={[13.19, 0.217, 0]} scale={1.5} />
    </group>
  )
}

useGLTF.preload('/train.gltf')
